apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_HOST: "mysql"
  MYSQL_USER: "myuser"
  MYSQL_DATABASE: "resultados_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3JkMTIz
  MYSQL_PASSWORD: bXlwYXNzd29yZDEyMw== 