apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS resultados_db;
    USE resultados_db;
    CREATE TABLE IF NOT EXISTS resultados (
      id INT AUTO_INCREMENT PRIMARY KEY,
      operacion VARCHAR(50),
      resultado FLOAT,
      fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ); 